-- -- Insert a set of records.
-- INSERT INTO burgers (name, devoured) VALUES ('Bacon Cheeseburger.', false);
-- INSERT INTO burgers (name, devoured) VALUES ('Jelly Bean Milksteak.', false);
-- INSERT INTO burgers (name, devoured) VALUES ('Steamed Hams.', false);
